import type { AccountsSummary } from "./types";

export const ACCOUNTS_DEMO: AccountsSummary = {
  lastSynchronized: "Today, 10:42 AM",
  kpis: [
    {
      id: "total-balance",
      label: "Total Balance",
      value: 4250000,
      currency: "QAR",
      icon: "account_balance_wallet",
      iconClassName: "bg-primary/5 text-primary",
      badge: "+2.4%",
      badgeClassName: "text-emerald-600 bg-emerald-50",
    },
    {
      id: "monthly-revenue",
      label: "Monthly Revenue",
      value: 850000,
      currency: "QAR",
      icon: "payments",
      iconClassName: "bg-secondary/5 text-secondary",
      badge: "This Month",
      badgeClassName: "text-on-surface-variant",
    },
    {
      id: "operating-expenses",
      label: "Operating Expenses",
      value: 320000,
      currency: "QAR",
      icon: "receipt_long",
      iconClassName: "bg-error/5 text-error",
      badge: "-5% vs target",
      badgeClassName: "text-error bg-error/5",
    },
    {
      id: "pending-payments",
      label: "Pending Payments",
      value: 125500,
      currency: "QAR",
      icon: "pending_actions",
      iconClassName: "bg-tertiary-container/10 text-primary",
      badge: "12 items",
      badgeClassName: "text-on-surface-variant",
    },
  ],
  bankAccounts: [
    {
      id: "qnb",
      shortName: "QNB",
      fullName: "Qatar National Bank",
      accountNumberMasked: "**** **** 8820",
      accountType: "Current",
      balance: 2840000,
      currency: "QAR",
      accentClassName: "bg-primary",
      icon: "account_balance",
      iconClassName: "text-primary",
      category: "BANK",
    },
    {
      id: "qib",
      shortName: "QIB",
      fullName: "Qatar Islamic Bank",
      accountNumberMasked: "**** **** 4109",
      accountType: "Savings",
      balance: 1120500,
      currency: "QAR",
      accentClassName: "bg-secondary",
      icon: "verified_user",
      iconClassName: "text-secondary",
      category: "BANK",
    },
    {
      id: "cbq",
      shortName: "CBQ",
      fullName: "Commercial Bank of Qatar",
      accountNumberMasked: "**** **** 0032",
      accountType: "Current",
      balance: 289500,
      currency: "QAR",
      accentClassName: "bg-on-surface",
      icon: "account_balance",
      iconClassName: "text-on-surface",
      category: "BANK",
    },
  ],
  transactions: [
    {
      id: "tx-1",
      date: "Oct 24, 2023",
      description: "Ooredoo Qatar - Monthly Bill",
      category: "Utilities",
      amount: -1250,
      currency: "QAR",
      status: "Completed",
      type: "debit",
    },
    {
      id: "tx-2",
      date: "Oct 23, 2023",
      description: "Service Fee Payment - Client ID #290",
      category: "Revenue",
      amount: 12500,
      currency: "QAR",
      status: "Completed",
      type: "credit",
    },
    {
      id: "tx-3",
      date: "Oct 22, 2023",
      description: "Staff Payroll - October 2023",
      category: "Payroll",
      amount: -45000,
      currency: "QAR",
      status: "Pending",
      type: "debit",
    },
    {
      id: "tx-4",
      date: "Oct 21, 2023",
      description: "Amazon Web Services - Cloud",
      category: "Technology",
      amount: -4800,
      currency: "QAR",
      status: "Completed",
      type: "debit",
    },
    {
      id: "tx-5",
      date: "Oct 20, 2023",
      description: "Inter-account Transfer: QIB to QNB",
      category: "Transfer",
      amount: 50000,
      currency: "QAR",
      status: "Completed",
      type: "transfer",
    },
    {
      id: "tx-6",
      date: "Oct 19, 2023",
      description: "Office Rent - West Bay Tower",
      category: "Facilities",
      amount: -18500,
      currency: "QAR",
      status: "Completed",
      type: "debit",
    },
    {
      id: "tx-7",
      date: "Oct 18, 2023",
      description: "Client Retainer - Al Rayyan Project",
      category: "Revenue",
      amount: 75000,
      currency: "QAR",
      status: "Completed",
      type: "credit",
    },
    {
      id: "tx-8",
      date: "Oct 17, 2023",
      description: "Vehicle Fleet Insurance",
      category: "Insurance",
      amount: -9200,
      currency: "QAR",
      status: "Pending",
      type: "debit",
    },
    {
      id: "tx-9",
      date: "Oct 16, 2023",
      description: "WPS Salary Batch - Batch #442",
      category: "Payroll",
      amount: -128000,
      currency: "QAR",
      status: "Completed",
      type: "debit",
    },
    {
      id: "tx-10",
      date: "Oct 15, 2023",
      description: "Consulting Invoice #INV-2091",
      category: "Revenue",
      amount: 32000,
      currency: "QAR",
      status: "Completed",
      type: "credit",
    },
  ],
};
